server:
  port: 8080

spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/discord_clone
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
  banner: banner.txt
