server:
  port: ${BACKEND_PORT:8080}

spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:discord_clone}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: db/changelog/db.changelog-master.yaml

  banner: banner.txt

logging:
  level:
    ru.itis.backend: DEBUG

jwt:
  seed: ${JWT_SEED:superDuperSecureSeedForGeneratingJwt}
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}

websocket:
  allowed-origins: ${SERVER_URL:http://localhost:5173}